const woolFarmingArticles = [
    {
        id: 1,
        title: 'Optimizing Wool Production: A Modern Approach',
        author: 'Wool Innovations Research Group',
        date: 'Jan 5',
        imageUri: 'https://example.com/wool-production-image1.jpg',
        languages: ['English', 'Spanish'],
        readTime: '18 min read',
        content: `Explore the latest advancements in wool farming, from smart shearing techniques to sustainable grazing practices, as we delve into the future of eco-conscious and efficient wool production.`,
    },
    {
        id: 2,
        title: 'The Role of Technology in Sustainable Wool Farming',
        author: 'TechWool Solutions',
        date: 'Feb 12',
        imageUri: 'https://example.com/wool-technology-image2.jpg',
        languages: ['English', 'French'],
        readTime: '20 min read',
        content: `Discover how technology-driven solutions, including IoT-enabled monitoring and precision agriculture, are revolutionizing sustainable wool farming practices for the benefit of both farmers and sheep.`,
    },
    {
        id: 3,
        title: 'Eco-Friendly Wool: A Look into Sustainable Practices',
        author: 'GreenWool Initiatives',
        date: 'Mar 18',
        imageUri: 'https://example.com/eco-wool-image3.jpg',
        languages: ['English', 'German'],
        readTime: '15 min read',
        content: `Explore the eco-friendly side of wool farming, from responsible land management to ethical treatment of sheep, and learn how sustainable practices are shaping the future of the wool industry.`,
    },
    {
        id: 4,
        title: 'Advancements in Wool Shearing Technology',
        author: 'ShearTech Innovations',
        date: 'Apr 8',
        imageUri: 'https://example.com/wool-shearing-image4.jpg',
        languages: ['English', 'Italian'],
        readTime: '22 min read',
        content: `Dive into the world of wool shearing advancements, where robotics and precision control are enhancing efficiency and ensuring the welfare of sheep during the shearing process.`,
    },
    {
        id: 5,
        title: 'Genetic Insights: Breeding for Quality Wool',
        author: 'WoolGenetics Research Institute',
        date: 'May 14',
        imageUri: 'https://example.com/wool-genetics-image5.jpg',
        languages: ['English', 'Chinese'],
        readTime: '19 min read',
        content: `Discover how genetic technologies are driving selective breeding programs to produce sheep with desirable wool characteristics, contributing to the creation of high-quality and sought-after wool fibers.`,
    },
    {
        id: 6,
        title: 'Innovative Wool Farming Practices for the Future',
        author: 'FutureWool Solutions',
        date: 'Jun 9',
        imageUri: 'https://example.com/innovative-wool-farming-image6.jpg',
        languages: ['English', 'Japanese'],
        readTime: '17 min read',
        content: `Explore a vision of the future of wool farming, where innovation meets sustainability. From precision agriculture to futuristic breeding techniques, discover the cutting-edge practices shaping tomorrow's wool industry.`,
    },
    {
        id: 7,
        title: 'Wool and Biodiversity: A Holistic Approach',
        author: 'BioWool Conservationists',
        date: 'Jul 20',
        imageUri: 'https://example.com/wool-biodiversity-image7.jpg',
        languages: ['English', 'Spanish'],
        readTime: '16 min read',
        content: `Delve into the integral connection between wool farming and biodiversity conservation. Learn how sustainable practices contribute to healthier ecosystems, supporting not only sheep but the entire environment.`,
    },
    {
        id: 8,
        title: 'Revolutionizing Wool Processing Techniques',
        author: 'Wool Processing Innovators',
        date: 'Aug 14',
        imageUri: 'https://example.com/wool-processing-image8.jpg',
        languages: ['English', 'French'],
        readTime: '21 min read',
        content: `Discover the latest innovations in wool processing, from efficient cleaning methods to advanced spinning technologies, and explore how these advancements are reshaping the processing stage of wool production.`,
    },
    {
        id: 9,
        title: 'Wool and Water Conservation: A Sustainable Approach',
        author: 'AquaWool Stewards',
        date: 'Sep 5',
        imageUri: 'https://example.com/wool-water-conservation-image9.jpg',
        languages: ['English', 'Italian'],
        readTime: '23 min read',
        content: `Uncover the importance of water conservation in wool farming. Explore sustainable water management practices that not only benefit wool production but also contribute to responsible and environmentally conscious farming.`,
    },
    {
        id: 10,
        title: 'Crafting Excellence: The Art of Wool Quality Assurance',
        author: 'QualityWool Guild',
        date: 'Oct 10',
        imageUri: 'https://example.com/wool-quality-assurance-image10.jpg',
        languages: ['English', 'German'],
        readTime: '18 min read',
        content: `Delve into the meticulous process of wool quality assurance. From rigorous testing methods to ensuring ethical practices, learn how the wool industry is committed to delivering excellence in every fiber.`,
    },
];

export default woolFarmingArticles;
